#if !canImport(ObjectiveC)
import XCTest

extension AntiForgeryMiddlewareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AntiForgeryMiddlewareTests = [
        ("testPostWithoutTokens", testPostWithoutTokens),
        ("testPostWithSingleToken", testPostWithSingleToken),
        ("testPostWithTokens", testPostWithTokens),
        ("testToken", testToken),
    ]
}

extension AuthorizationMiddlewareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthorizationMiddlewareTests = [
        ("testMiddleware", testMiddleware),
    ]
}

extension CookiesMiddlewareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CookiesMiddlewareTests = [
        ("testMiddleware", testMiddleware),
    ]
}

extension UserManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserManagerTests = [
        ("testLogin", testLogin),
        ("testRegister", testRegister),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AntiForgeryMiddlewareTests.__allTests__AntiForgeryMiddlewareTests),
        testCase(AuthorizationMiddlewareTests.__allTests__AuthorizationMiddlewareTests),
        testCase(CookiesMiddlewareTests.__allTests__CookiesMiddlewareTests),
        testCase(UserManagerTests.__allTests__UserManagerTests),
    ]
}
#endif
