#if !canImport(ObjectiveC)
import XCTest

extension ApplicationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApplicationTests = [
        ("testConvenienceAPI", testConvenienceAPI),
        ("testPartialUrl", testPartialUrl),
    ]
}

extension ControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ControllerTests = [
        ("testContextResponse", testContextResponse),
        ("testInject2Services", testInject2Services),
        ("testInject3Services", testInject3Services),
        ("testInject4Services", testInject4Services),
        ("testInject5Services", testInject5Services),
        ("testInject6Services", testInject6Services),
        ("testInjectable", testInjectable),
        ("testInjectContext", testInjectContext),
        ("testInjectContextService", testInjectContextService),
        ("testInjectService", testInjectService),
    ]
}

extension MiddlewareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MiddlewareTests = [
        ("testMiddleware", testMiddleware),
        ("testMiddlewareOrder", testMiddlewareOrder),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ApplicationTests.__allTests__ApplicationTests),
        testCase(ControllerTests.__allTests__ControllerTests),
        testCase(MiddlewareTests.__allTests__MiddlewareTests),
    ]
}
#endif
